# Generated by Django 5.1.3 on 2024-11-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PROJECT_MANAGER', 'Project Manager'), ('CONTRIBUTOR', 'Contributor')], default='CONTRIBUTOR', max_length=15),
        ),
    ]
